export default {
  bail: true,
  clearMocks: true,
  collectCoverage: true,
  collectCoverageFrom: ["src/**/{!(fixture),}.js"],
  coverageDirectory: "coverage",
  coverageProvider: "babel",
  reporters: ["default", "jest-junit"],
  coverageReporters: [
    "clover",
    "html",
    "lcov",
    "json",
    "json-summary",
    "text",
    "text-summary",
  ],
  setupFilesAfterEnv: ["<rootDir>/src/resources/scripts/jest.setup.js"],
  moduleFileExtensions: ["js"],
  testEnvironment: "jsdom",
  testMatch: ["?(**/)*.test{!(fixture),}.js"],
  rootDir: ".",
  displayName: "JEST unit test",
  coverageThreshold: {
    global: {
      statements: 95,
      branches: 95,
      functions: 95,
      lines: 95,
    },
  },
  globals: { isolatedModules: true },
  transform: {
    ".js": "babel-jest",
    ".css": "jest-transform-css",
  },
  verbose: true,
};
