export default {
  bail: true,
  clearMocks: true,
  collectCoverage: true,
  collectCoverageFrom: ["src/**/*"],
  coverageDirectory: "coverage",
  coverageProvider: "babel",
  reporters: ["default", "jest-junit"],
  coverageReporters: ["json-summary", "text", "html", "text-summary"],
  setupFilesAfterEnv: ["./src/resources/scripts/jest.setup.js"],
  moduleFileExtensions: ["js"],
  testEnvironment: "jsdom",
  testMatch: ["*.(spec|test).js", "**/*.(spec|test).js"],
  // moduleNameMapper: { "\\.(c|sa)ss$": "src/**/*.fixture.js" },
  transform: { "\\.[jt]sx?$": "babel-jest" },
  verbose: true,
};
